name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Node.js for frontend
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm
              cache-dependency-path: frontend/package-lock.json

          - name: Install frontend dependencies
            working-directory: frontend
            run: npm install

          - name: Set up Node.js for backend
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm
              cache-dependency-path: backend/package-lock.json
          
          - name: Install backend dependencies
            working-directory: backend
            run: npm install

          # - name: Frontend Tests
          #   working-directory: frontend
          #   run: npm test
            
          # - name: Backend Tests
          #   working-directory: backend
          #   run: npm test